### ISSUE TITLE
Update fails if autoscend is installed via git checkout rather than SVN

### ISSUE THREAD

**Issue by magus-prime** [libraryaddict/KolLocket#2]
Yesterday I reinstalled autoscend using the new support for direct git checkouts in KoLmafia.  Today performing svn update on this script resulted in the following error:
`Update log for libraryaddict-KolLocket-branches-release:
------
Commit r67:
Author: build.script

Build Mafia files for commit 0f4b2eb8e7d7c1be229a551a8f1e1ec6d7fbb0b0
------
Validating repo...
svn: E160013: '/Loathing-Associates-Scripting-Society/autoscend/!svn/bc/7314/branches/master/RELEASE' path not found: 404 Not Found (https://github.com)
Something went wrong while fetching svn directory info
Dependency at https://github.com/Loathing-Associates-Scripting-Society/autoscend/branches/master/RELEASE failed validation. Won't be processed.`

**Comment by libraryaddict** [comment]
This is a mafia bug at most.

**Comment by magus-prime** [comment]
I apologize.  It isn't this script that's trying to install autoscend as a dependancy it was the next script in line.
