### ISSUE TITLE
"locket all" produces list missing entire sections of monsters?

### ISSUE THREAD

**Issue by Tokoeka** [libraryaddict/KolLocket#3]
When I do "locket all", it provides a long list of monsters, which appears to have entire sections missing. Doing it today, you can see there is a large gap in the alphabetical sorting between where the first sction ends with "Drink-delivery trainbot" and where the next picks up with "medium-sized barrel mimic", and again where that one ends with "slag-processing trainbot" and the next picks up with "wine-pairing trainbot".

From going through many zones with "locket zone" and adding monsters to the locket_monsters.txt file, i can confidently state that there are multiple monsters in these "gaps" that are not being displayed (for some non-exhaustive examples, I have collected none of the Dyspepsi-cola monsters from the temporal rift, and I am still missing a large number of "war-frat" monsters from the island war). In addition, it is obviously finding more monsters from the count it is providing: 1093/1300 means there should be 207 monsters listed, but there are only 110 from what I can tell. 

I am fairly certain that it is finding them (not least because where the breaks in the chain are change as I locket monsters (will add evidence tomorrow, i forgot to do so today), just choosing not to display them for reasons I cannot see.

![image](https://github.com/libraryaddict/KolLocket/assets/82226562/227a9e08-6cfb-413e-b547-aa0db98d7e6e)

**Comment by Tokoeka** [comment]
after fighting a depressing French accordionit, a lively Cajun accordionist, and a clod hopper, "locket all" provides the below, which has 3 less monsters in the final block of monsters, but the other two blocks appear to include the same amount, with different entries where the list has moved up, and including monsters that werent in the previous list (dropped base, drunk duck, sleaze hobo, sleepy mariachi, small barrel mimic)

![image](https://github.com/libraryaddict/KolLocket/assets/82226562/b4a4bf2f-683f-48ec-bd18-52d430640d51)

**Comment by libraryaddict** [comment]
Unfortunately the fact is that the monsters that can be locketed is not reliable. There's no way we can determine if a monster can or cannot be locketed.

We know an ultra rare monster obviously can't be locketed, we know _most_ bosses can't be locketed.

We know some wishable monsters can't be locketed.. And yet, some unwishable monsters can. (citation required)

I do agree that its a bug, I just unfortunately can't really do much about this. The most obvious solution is to user-source lists of known locketable and unlocketable monsters.
Which could be an idea I suppose, but mafia's limitations makes it a bit eh. I'll take a poke and see how bad that is I guess

**Comment by libraryaddict** [comment]
Yeah, going through it there is a solution somewhat.

It would be parsing your session logs, it does seem to note when the monster is no-copy.
So we'd

1. Look at your locket to see what is copyable
2. Parse session logs to see what is no-copy `After Battle: Your locket vibrates -- memories of this monster would be too painful to revisit.`
3. Store this data, and generate a list of monsters to try
4. Everytime you look at the data, we scan the session logs again and your locket again and update the list of monsters to remove the monsters that were attempted.

This is probably the only real solution. Though my biggest thought here is some verification that the "too painful" is the same monster we're fighting, because of something like backup camera. Perhaps just verifying that the last damaging blow is the monster name.

**Comment by Tokoeka** [comment]
I'm not querying a discrepancy of "there are monsters that are copyable that are not on the list", I am querying the fact that it appears kolLocket is producing a list (when you do locket all) and then only printing sections of said list - as evidenced by the fact that monsters that were not on the list two days ago, appeared on the list yesterday after other monsters were removed.

**Comment by Tokoeka** [comment]
Based on the monster count it is providing, I believe KolLocket is indicating there are 200ish monsters on the list (whether they should be copyable or not), and then only printing 100-odd of them

**Comment by Tokoeka** [comment]
Hopefully this will make it clearer.

What Locket All showed at start of day:
![image](https://github.com/libraryaddict/KolLocket/assets/82226562/68a4f662-4afa-4cb8-a9ff-219626984de6)

After defeating a monkey-wrenchin' elf:
![image](https://github.com/libraryaddict/KolLocket/assets/82226562/38dae26d-ba4e-42db-b90e-7df8a5489839)
(Sorority Nurse has appended itself to the end of the second section, despite (apparently) not being in the list at the start of day, Zombie eXtreme snowboarding orc has disappeared from 3rd section)

After defeating a skeleton invader:
![image](https://github.com/libraryaddict/KolLocket/assets/82226562/c93950ac-49e8-4b30-a10f-16ceef6b1681)
(Sorority operator has appended itself to the end of the second section, zombie Goth Giant has disappeared - removing the 3rd section altogether)

After defeating an angry raccoon puppet:
![image](https://github.com/libraryaddict/KolLocket/assets/82226562/fe052ab2-ea72-4e00-a6d6-feb835a94f6b)
(Dyspepsi-Cola Knight has appended itself to the end of the first section, morbid skull has disappeared from start of second section, Space Marine has appended itself to end of second section)

After defeating a business hippy
![image](https://github.com/libraryaddict/KolLocket/assets/82226562/1a83e5d9-9056-49c5-9cee-469cf903a670)
(Dyspepsi-Cola Soldier has appended itself to end of 1st section, mounted lawn gnome has disappeared from start of second section, spirit faucet has appended itself to end of second section)

To clarify, i believe it is only printing the first and then every second "section" thereafter of the list it generates

**Comment by libraryaddict** [comment]
Fixed for realsies now
